#!/bin/bash
# Создает архивы для распространения SBo_Port_script
# 1 Коллекции сценариев SBo_Port_script;
# 2 Коллекции портов SBo_Port_port;
# 3 Коллекции пакетов SBo_Port_pkg;
# 4 Коллекции с исходными текстами программ SBo-Port_source.

source /etc/SBo_Port_script/SW_pkg.conf
source /usr/lib/SBo_Port_script/SW_pkg_functions

if test -z "$1"
then
  echo "Аргументы командной строки отсутствуют. Используемый номер версии $SBOPORT_VERSION"
  create_SBo_Port_arcs $SBOPORT_VERSION
else
  echo "Первый аргумент командной строки: Используемый номер версии $1"
  create_SBo_Port_arcs $1
fi

