#!/bin/bash
PKG="SBo_Port_script"

rm -r /usr/lib/${PKG}/
rm -r /etc/${PKG}/

sed "/export PATH=\$PATH:\/usr\/lib\/${PKG} # ${PKG} setup line. Please do not correct or erase this line./d" ~/.profile > ~/.profile.tmp
rm ~/.profile
cp ~/.profile.tmp ~/.profile
rm ~/.profile.tmp

 